### ISSUE TITLE
Not working with new runtime

### ISSUE THREAD

**Issue by sven5** [anzharip/azure-function-multipart#373]
Yesterday, I've updated to the new Azure Functions Core Tools

Azure Functions Core Tools
Core Tools Version:       4.0.4544 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.3.2.18186

It seems that busboy has some problems, the events don't get fired any more and the functions runs endlessly. 
I'm currently trying to find the root cause.
It doesn't work locally neither on Azure.

**Comment by sven5** [comment]
Find an issue:
Perhaps, you should invoke `busboy.end()` after `busboy.write(...)`

**Comment by anzharip** [comment]
Fixed on https://github.com/anzharip/azure-function-multipart/commit/90b07550c1fbb2709d213b4249bab7ba49c54aa5

**Comment by sven5** [comment]
@anzharip  Sorry for being late, I was on holidays. 
Currently, I've installed busboy v1.6.0

However, the busboy guys [recommends](https://github.com/mscdex/busboy/issues/301) to always use `end()`
