### ISSUE TITLE
How can I use this with CommonJS?

### ISSUE THREAD

**Issue by hanktrizz** [anzharip/azure-function-multipart#88]
Hi, I browsed your library and I feel that it might help me solve a direct issue I'm having with multipart form data. However, I can't import using CommonJS and I don't have the liberty of upgrading the runtime to support ES Modules. Is there a way I could bypass the problem and if not, do you think you could support this? Thanks.

**Comment by anzharip** [comment]
@hanktrizz glad that this module helps! I think it should be possible to use it in CommonJS style, as the TS compiler settings export the code as CommonJS module. I'll give it a shot and give a bit of sample for you to start later.

**Comment by anzharip** [comment]
Closed for inactivity
